version: '3'
services:
  back:
    build: ./back
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      REV_AI_KEY: 028IAXWXIm71lWStMgG_Mr-FBBbO3skk7Wyf_3ZEX1M4kHVRDU_BVkd9e066BZymI6fqR8cUCTlim-AHL4hERxOCbFyQc
  front:
    build: ./front
    ports: 
      - "8080:80"
  engine:
    build: ./engine
    volumes:
      - ./engine/data:/data
  db:
    image: mongo
  db-seed:
    build:
      context : ./db
      dockerfile : Dockerfile.seed
  db-viewer:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_SITE_BASEURL: /dbviewer/